apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: votogen-back
spec:
  replicas: 1
  selector:
    matchLabels:
      name: votogen-back
  template:
    metadata:
      name: votogen-back
      labels:
        name: votogen-back
    spec:
      containers:
      - name: votogen-back
        image: votogen/votogen-back:__CI_IMAGE_TAG__
        ports:
        - name: http
          containerPort: 80
        imagePullPolicy: IfNotPresent
        env:
          - name: SYSTEM_ENVIRONMENT
            value: "production"
          - name: DATASOURCE_URL
            value: "jdbc:mysql://199.189.87.11/votogen?autoReconnect=true&useSSL=false"
          - name: DATASOURCE_USERNAME
            value: "votogen"
          - name: DATASOURCE_PASSWORD
            value: "wSHWsX3JyEQHOdzt7g5W"
          - name: JAVA_OPTS
            value: "-Dserver.port=80"
---
apiVersion: v1
kind: Service
metadata:
  name: votogen-back
  labels:
    name: votogen-back
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    name: votogen-back
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: votogen-back
spec:
  rules:
  - host: votogenapi.condor1693.dedicatedpanel.com
    http:
      paths:
      - path:
        backend:
          serviceName: votogen-back
          servicePort: 80