spring:
  profiles: production
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    database: MYSQL
    generate-ddl: true
    ddl-auto: update

server:
  port: 8080